# 🐼 Pandas
Pandas is a powerful Python library used for working with tabular data (data in rows and columns).
- It provides a structure called a DataFrame, which looks like a table.
- Each column in a DataFrame is called a Series, not a list, and can hold different data types.
-  Pandas makes it easy to load, filter, analyze, and manipulate large datasets efficiently.

In [87]:
# importing pandas
import pandas as pd

If you want to create your own dataframe, create a dictionary, then use pd.DataFrame function

In [88]:
new_data = {'name': ['ahmed', 'ali', 'mona'],
            'age': [20, 22, 19],
            'country': ['egypt', 'Iraq', 'Sudan']}
my_data = pd.DataFrame(new_data)

In [89]:
print(type(my_data))

<class 'pandas.core.frame.DataFrame'>

In [90]:
my_data

    name  age country
0  ahmed   20   egypt
1    ali   22    Iraq
2   mona   19   Sudan

In [91]:
file_id = '18Aie7PXX77qZj1mFHp2YXw-gzBstu19p'
url = f"https://drive.google.com/uc?export=download&id={file_id}"

#Reading and discovering Data

In [92]:
# reading the data
data = pd.read_csv(url)
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [93]:
temp = data.copy()
temp.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [94]:
data.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [95]:
data.shape

(545, 13)

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [97]:
data.shape

(545, 13)

In [98]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [99]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [100]:
data['area'].isnull().sum()

np.int64(0)

In [101]:
data.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [102]:
data.describe(include='object')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227

In [103]:
data['bedrooms'] = data['bedrooms'].astype('int')
data.describe(include='object')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227

Here we wanted to treat 'bedrooms' column as a category, so we used **astype()**method to change its datatype

In [104]:
data.select_dtypes(include='object')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
0,yes,no,no,no,yes,yes,furnished
1,yes,no,no,no,yes,no,furnished
2,yes,no,yes,no,no,yes,semi-furnished
3,yes,no,yes,no,yes,yes,furnished
4,yes,yes,yes,no,yes,no,furnished
...,...,...,...,...,...,...,...
540,yes,no,yes,no,no,no,unfurnished
541,no,no,no,no,no,no,semi-furnished
542,yes,no,no,no,no,no,unfurnished
543,no,no,no,no,no,no,furnished
544,yes,no,no,no,no,no,unfurnished

In [105]:
cat_cols = list(data.select_dtypes(include='object').columns)

In [106]:
data.select_dtypes(include='int') # This is if we want to show columns with specific data type

        price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [107]:
data['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [108]:
data['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [109]:
data.nunique()

price               219
area                284
bedrooms              6
bathrooms             4
stories               4
mainroad              2
guestroom             2
basement              2
hotwaterheating       2
airconditioning       2
parking               4
prefarea              2
furnishingstatus      3
dtype: int64

#Subsetting Columns in Pandas

In [110]:
data['price']

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [111]:
data[['price', 'area', 'bedrooms']]

        price  area  bedrooms
0    13300000  7420         4
1    12250000  8960         4
2    12250000  9960         3
3    12215000  7500         4
4    11410000  7420         4
..        ...   ...       ...
540   1820000  3000         2
541   1767150  2400         3
542   1750000  3620         2
543   1750000  2910         3
544   1750000  3850         3

[545 rows x 3 columns]

#Subsetting Rows in Pandas

1- Slicing

In [112]:
data[2:5]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

2- Boolian Indexing

In [113]:
data['area'] > 7000         # returns a boolian series
data[data['area'] > 7000 ]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,3500000,12944,3,1,1,yes,no,no,no,no,0,no,unfurnished
452,3150000,9000,3,1,2,yes,no,no,no,no,2,no,semi-furnished
460,3087000,8100,2,1,1,yes,no,no,no,no,1,no,unfurnished
473,3003000,8050,2,1,1,yes,no,no,no,no,0,no,unfurnished
520,2450000,7700,2,1,1,yes,no,no,no,no,0,no,unfurnished

In [114]:
data[data['price'] > 150000 ]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [115]:
data[(data['price']> 150000) & (data['mainroad'] == 'yes') ]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [116]:
data[((data['area'] > 7000) & (data['bathrooms'] > 3)) | (data['furnishingstatus'] == 'furnished')]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,2590000,3600,2,2,2,yes,no,yes,no,no,1,no,furnished
512,2520000,3000,2,1,2,yes,no,no,no,no,0,no,furnished
522,2380000,2475,3,1,2,yes,no,no,no,no,0,no,furnished
523,2380000,2787,4,2,2,yes,no,no,no,no,0,no,furnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished

# Access rows and columns using 'loc' and 'iloc'

**1- .loc[ ] — label-based access**

Access a single row

In [117]:
# data[1] this will raise an error
data.loc[1]

price                12250000
area                     8960
bedrooms                    4
bathrooms                   4
stories                     4
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     3
prefarea                   no
furnishingstatus    furnished
Name: 1, dtype: object

Access a single value (one cell)

In [118]:
data.loc[0, 'area'] # the value of area for the second house

np.int64(7420)

Access multiple rows and columns:

In [119]:
data.loc[[0,1,3], ['price','bedrooms']]

      price  bedrooms
0  13300000         4
1  12250000         4
3  12215000         4

In [120]:
data[0:3][['price', 'bedrooms']] # without loc

      price  bedrooms
0  13300000         4
1  12250000         4
2  12250000         3

**2- .iloc[ ] — position-based access**

Acecss single row

In [121]:
data.iloc[5]

price                     10850000
area                          7500
bedrooms                         3
bathrooms                        3
stories                          1
mainroad                       yes
guestroom                       no
basement                       yes
hotwaterheating                 no
airconditioning                yes
parking                          2
prefarea                       yes
furnishingstatus    semi-furnished
Name: 5, dtype: object

Access a single value

In [122]:
data.iloc[0, 1]

np.int64(7420)

Access multiple rows and columns:

In [123]:
data.iloc[1:3, 2:5]

   bedrooms  bathrooms  stories
1         4          4        4
2         3          2        2

#Aggregation in pandas

In [124]:
avg = data['price'].mean()
avg

np.float64(4766729.247706422)

In [125]:
max = data['price'].max()
max

13300000

In [126]:
data[['mainroad', 'guestroom']].mode()

  mainroad guestroom
0      yes        no

In [127]:
(data['bedrooms'] < 2).sum()

np.int64(2)

**agg() method**: used when we want to apply multiple functions or different function for each column

In [128]:
data['price'].agg('mean')

np.float64(4766729.247706422)

In [129]:
data['area'].agg(['mean', 'min', 'max'])

mean     5150.541284
min      1650.000000
max     16200.000000
Name: area, dtype: float64

In [130]:
# pd.set_option('display.float_format', '{:.0f}'.format)

In [131]:
data.agg({'price': 'median', 'area': 'mean'})

price    4.340000e+06
area     5.150541e+03
dtype: float64

# Group by

Without groupby

In [132]:
f1 = data[data['furnishingstatus'] == 'furnished']['price'].max()
f2 = data[data['furnishingstatus'] == 'semi-furnished']['price'].max()
f3 = data[data['furnishingstatus'] == 'unfurnished']['price'].max()
print(f1, f2, f3)

13300000 12250000 10150000

With groupby

In [133]:
data.groupby('furnishingstatus')['price'].mean()

furnishingstatus
furnished         5.495696e+06
semi-furnished    4.907524e+06
unfurnished       4.013831e+06
Name: price, dtype: float64

In [134]:
data.groupby('furnishingstatus')['price'].agg(['min', 'max'])

                      min       max
furnishingstatus
furnished         1750000  13300000
semi-furnished    1767150  12250000
unfurnished       1750000  10150000

In [135]:
data.groupby(['furnishingstatus', 'airconditioning'])['price'].mean()

furnishingstatus  airconditioning
furnished         no                 4.469500e+06
                  yes                6.786717e+06
semi-furnished    no                 4.557951e+06
                  yes                5.778769e+06
unfurnished       no                 3.583342e+06
                  yes                5.286167e+06
Name: price, dtype: float64

# Common String Functions

In [136]:
data['furnishingstatus'] = data['furnishingstatus'].str.upper()
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,FURNISHED
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,FURNISHED
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,SEMI-FURNISHED
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,FURNISHED
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,FURNISHED

In [137]:
data['furnishingstatus'] = data['furnishingstatus'].str.lower()
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [138]:
data['furnishingstatus'] = data['furnishingstatus'].str.strip()
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [139]:
data[data['furnishingstatus'].str.contains('semi|SEMI')]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semi-furnished
12,9310000,6550,4,2,2,yes,no,no,no,yes,1,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,2660000,3480,2,1,1,yes,no,no,no,no,1,no,semi-furnished
503,2660000,4000,3,1,1,yes,no,no,no,no,0,no,semi-furnished
514,2485000,3000,3,1,2,no,no,no,no,no,0,no,semi-furnished
527,2275000,1836,2,1,1,no,no,yes,no,no,0,no,semi-furnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished

In [140]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

#Some other Functions

In [141]:
yes_no = {'yes': 1, 'no': 0}
data['guestroom'] = data['guestroom'].replace(yes_no)
data.head()

/tmp/ipykernel_2687/514297873.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['guestroom'] = data['guestroom'].replace(yes_no)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,0,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,0,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,0,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,0,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,1,yes,no,yes,2,no,furnished

In [84]:
data['area'].apply(lambda x: x/100)

0      74.2
1      89.6
2      99.6
3      75.0
4      74.2
       ...
540    30.0
541    24.0
542    36.2
543    29.1
544    38.5
Name: area, Length: 545, dtype: float64

In [85]:
data['guestroom'].replace('no', 'not found')

0      0
1      0
2      0
3      0
4      1
      ..
540    0
541    0
542    0
543    0
544    0
Name: guestroom, Length: 545, dtype: int64

In [142]:
data['bathrooms'] = data['bathrooms'].where(data['bathrooms'] > 2, 'less than 2')
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,less than 2,3,yes,0,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,0,no,no,yes,3,no,furnished
2,12250000,9960,3,less than 2,2,yes,0,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,less than 2,2,yes,0,yes,no,yes,3,yes,furnished
4,11410000,7420,4,less than 2,2,yes,1,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,less than 2,1,yes,0,yes,no,no,2,no,unfurnished
541,1767150,2400,3,less than 2,1,no,0,no,no,no,0,no,semi-furnished
542,1750000,3620,2,less than 2,1,yes,0,no,no,no,0,no,unfurnished
543,1750000,2910,3,less than 2,1,no,0,no,no,no,0,no,furnished
544,1750000,3850,3,less than 2,2,yes,0,no,no,no,0,no,unfurnished



---

Excercise 1 :

- Filter the dataset to include only premium properties, guestroom, area greater than 3000 , and include air conditioning

- Then group the filtered data by furnishingstatus and compute: the average price, The average number of bedrooms, **The** count of such premium properties in each furnishing category

Excercise2:

- Create a new column called energy_load, calculated as:
[energy_load = (area * 0.5) + (bedrooms * 100) + (bathrooms * 150)]

- Filter the data to include only houses that:

1. Have airconditioning == 'yes'

2. Have hotwaterheating == 'yes'



- Group the filtered data by furnishingstatus and compute:

1. Average energy_load

2. Average price